from cornflow_client.constants import (
    SOLUTION_STATUS_FEASIBLE,
    SOLUTION_STATUS_INFEASIBLE,
    STATUS_FEASIBLE,
    STATUS_TIME_LIMIT,
    STATUS_NODE_LIMIT,
)

STATUS_ITERATION_LIMIT = 6
STATUS_USER_INTERRUPT = 7
